// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: delete_users.sql

package database

import (
	"context"
)

const deleteUsers = `-- name: DeleteUsers :exec
delete from users where 1=1
`

func (q *Queries) DeleteUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUsers)
	return err
}
