// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: expire_token.sql

package database

import (
	"context"
)

const expireRefreshToken = `-- name: ExpireRefreshToken :exec
update refresh_tokens set revoked_at = now(), updated_at=now()
where token = $1
`

func (q *Queries) ExpireRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, expireRefreshToken, token)
	return err
}
